# Generated by Django 3.2.4 on 2021-06-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.picture')),
            ],
        ),
    ]
