# Generated by Django 3.2.4 on 2021-06-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='t_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
