# Generated by Django 3.2.4 on 2021-06-21 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='expires',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
