# Generated by Django 3.2.4 on 2021-06-20 14:02

import api.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumb',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=1, upload_to=api.models.thumb_dir_path),
            preserve_default=False,
        ),
    ]
