# Generated by Django 3.2.4 on 2021-06-21 12:40

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
