# Generated by Django 3.2.4 on 2021-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_picture_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbnail',
            name='t_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.URLField(),
        ),
    ]
