# Generated by Django 3.2.4 on 2021-06-21 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='expires',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
