# Generated by Django 3.2.4 on 2021-06-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_thumbnail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='duration',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
