# Generated by Django 3.2.4 on 2021-06-20 20:39

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 20, 20, 39, 13, 283814)),
        ),
        migrations.AddField(
            model_name='picture',
            name='expires',
            field=models.IntegerField(default=300, verbose_name=models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)])),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='api.picture'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='url',
            field=models.ImageField(upload_to=''),
        ),
    ]
