# Generated by Django 3.2.4 on 2021-06-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_thumbnail_t_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='t_url',
        ),
    ]
