# Generated by Django 3.2.4 on 2021-06-23 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210623_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='url',
        ),
    ]
